import { useMemo } from 'react';
import { Link } from 'wouter';
import { useGetDashboard, useListConversations } from '@workspace/api-client-react';
import { ArrowRight, Clock3, MessageSquare, Plus, Search, Sparkles } from 'lucide-react';
import { AppShell, PageEyebrow } from '@/components/askflow-shell';

function formatDate(date: string) {
  const value = new Date(date);
  if (Number.isNaN(value.getTime())) return 'Recently';
  return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(value);
}

function LoadingDashboard() {
  return <div className="mx-auto max-w-5xl animate-pulse px-5 py-10 md:px-10 md:py-14"><div className="h-3 w-20 rounded bg-muted" /><div className="mt-5 h-14 max-w-sm rounded bg-muted" /><div className="mt-12 grid gap-4 md:grid-cols-3"><div className="h-32 rounded-xl bg-muted" /><div className="h-32 rounded-xl bg-muted" /><div className="h-32 rounded-xl bg-muted" /></div></div>;
}

export function DashboardPage() {
  const dashboard = useGetDashboard();
  const conversations = useListConversations();
  const items = conversations.data || [];
  const latest = useMemo(() => [...items].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()).slice(0, 4), [items]);

  return <AppShell>{dashboard.isLoading ? <LoadingDashboard /> : <div className="mx-auto max-w-5xl px-5 py-10 md:px-10 md:py-14">
    <div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="animate-rise"><PageEyebrow>Your thinking space</PageEyebrow><h1 data-testid="text-dashboard-greeting" className="mt-4 font-editorial text-5xl leading-[.96] tracking-[-.045em] sm:text-6xl">{dashboard.data?.user?.name ? `Good to see you, ${dashboard.data.user.name.split(' ')[0]}.` : 'Make some room to think.'}</h1><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">Useful answers, saved where you can find them. Start with a question that has been waiting for your attention.</p></div><Link href="/chat" data-testid="link-start-conversation" className="group inline-flex h-11 items-center justify-center gap-2 self-start rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground transition hover:-translate-y-0.5 sm:self-auto"><Plus className="size-4" />Start thinking<ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link></div>
    {dashboard.isError && <div data-testid="status-dashboard-error" className="mt-8 flex items-center justify-between rounded-xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-xs text-destructive"><span>We couldn't load your overview.</span><button type="button" data-testid="button-retry-dashboard" onClick={() => dashboard.refetch()} className="font-bold underline">Try again</button></div>}
    <div className="mt-12 grid gap-4 sm:grid-cols-2 md:grid-cols-3">
      <div className="rounded-xl border border-card-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><p className="font-mono-ui text-[10px] uppercase tracking-[.12em] text-muted-foreground">Conversations</p><MessageSquare className="size-4 text-accent" /></div><p data-testid="text-total-conversations" className="mt-5 font-editorial text-5xl tracking-[-.04em]">{dashboard.data?.totalConversations ?? items.length}</p><p className="mt-1 text-xs text-muted-foreground">Questions kept in one place</p></div>
      <div className="rounded-xl border border-card-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><p className="font-mono-ui text-[10px] uppercase tracking-[.12em] text-muted-foreground">Workspace</p><Sparkles className="size-4 text-accent" /></div><p className="mt-5 font-editorial text-4xl tracking-[-.04em]">Quiet</p><p className="mt-2 text-xs text-muted-foreground">A clear surface for useful work</p></div>
      <div className="rounded-xl border border-card-border bg-primary p-5 text-primary-foreground shadow-sm sm:col-span-2 md:col-span-1"><p className="font-mono-ui text-[10px] uppercase tracking-[.12em] text-primary-foreground/60">A small prompt</p><p className="mt-4 font-editorial text-2xl leading-tight">“What would make this simpler?”</p><Link href="/chat" data-testid="link-prompt-card" className="mt-5 inline-flex items-center gap-1.5 text-xs font-bold text-accent">Open a blank page <ArrowRight className="size-3.5" /></Link></div>
    </div>
    <div className="mt-14 flex items-end justify-between border-b border-border pb-4"><div><PageEyebrow>Recent conversations</PageEyebrow><h2 className="mt-2 font-editorial text-3xl tracking-[-.03em]">Pick up where you left off.</h2></div><Link href="/chat" data-testid="link-view-all" className="hidden items-center gap-1.5 text-xs font-bold text-primary sm:flex">View all <ArrowRight className="size-3.5" /></Link></div>
    {conversations.isLoading ? <div className="space-y-2 pt-3">{[1,2,3].map((item) => <div key={item} className="h-[68px] animate-pulse rounded-lg bg-muted" />)}</div> : conversations.isError ? <div data-testid="status-conversations-error" className="py-10 text-center text-sm text-muted-foreground">Conversations are taking a moment to arrive. <button type="button" data-testid="button-retry-conversations" onClick={() => conversations.refetch()} className="font-bold text-primary underline">Retry</button></div> : latest.length ? <div className="divide-y divide-border/70">{latest.map((conversation, index) => <Link href={`/chat/${conversation.id}`} key={conversation.id} data-testid={`card-conversation-${conversation.id}`} className="group flex items-center gap-4 py-4 transition hover:px-2"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-primary"><MessageSquare className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{conversation.title || 'Untitled thought'}</p><p className="mt-1 flex items-center gap-2 text-[11px] text-muted-foreground"><span>{conversation.messageCount} {conversation.messageCount === 1 ? 'message' : 'messages'}</span><span className="size-0.5 rounded-full bg-muted-foreground" /><span>{formatDate(conversation.updatedAt)}</span></p></div><span className="hidden font-mono-ui text-[10px] text-muted-foreground/50 sm:block">0{index + 1}</span><ArrowRight className="size-4 -translate-x-1 text-muted-foreground opacity-0 transition group-hover:translate-x-0 group-hover:opacity-100" /></Link>)}</div> : <div data-testid="empty-conversations" className="flex flex-col items-center py-16 text-center"><div className="flex size-12 items-center justify-center rounded-full bg-muted"><Search className="size-5 text-muted-foreground" /></div><h3 className="mt-4 text-sm font-bold">Nothing here yet.</h3><p className="mt-1 max-w-xs text-xs leading-5 text-muted-foreground">Your first useful answer is one question away.</p><Link href="/chat" data-testid="link-empty-start" className="mt-5 text-xs font-bold text-primary underline">Begin a conversation</Link></div>}
    <div className="mt-12 flex items-center gap-2 text-[11px] text-muted-foreground"><Clock3 className="size-3.5" />Your conversation history is private to this workspace.</div>
  </div>}</AppShell>;
}